### ISSUE TITLE
[Sign & Submit] Verify alerts for missing Institution info

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#1053]
- [x] LEI
- [x] TIN
- [x] Types of Financial Institution

**Comment by meissadia** [comment]
This is a mocked scenario only to demonstrate what would be displayed for these data fields were they to be returned unpopulated from the Institution API on the `Sign & Submit` page
![screencapture-localhost-8899-filing-2024-123456789TESTBANK123-submit-2024-11-13-12_55_46](https://github.com/user-attachments/assets/37e21fc9-f4a9-406f-a699-04c8ca4ceee7)

**Comment by natalia-fitzgerald** [comment]
@meissadia 
- Change label to "LEI registration status"
- Change to error (red) instead of warning (gold)
- If Type of financial institution is missing wouldn't this indicate a larger scale problem and perhaps the page wouldn't load the filing information? 

<img width="445" alt="Screenshot 2024-11-14 at 5 14 48 PM" src="https://github.com/user-attachments/assets/05fdaaca-89c1-44ab-827a-b7476aaa92cb">
<img width="477" alt="Screenshot 2024-11-14 at 5 15 02 PM" src="https://github.com/user-attachments/assets/4188fca7-a08e-4879-aa34-4a27a483e60e">
<img width="671" alt="Screenshot 2024-11-14 at 5 17 58 PM" src="https://github.com/user-attachments/assets/0868a500-8777-49df-a932-971bde32a30f">

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Is this completed?

**Comment by meissadia** [comment]
> @meissadia Is this completed?

Still pending review and needs a couple of updates to get the code in sync with the `main` branch.  I will pick this back up tomorrow (Dec 5th).

**Comment by meissadia** [comment]
> > @meissadia Is this completed?
> 
> Still pending review and needs a couple of updates to get the code in sync with the `main` branch. I will pick this back up tomorrow (Dec 5th).

Merge conflicts in the PR have been resolved.  I will follow-up with the Frontend team to get these changes pushed through.
