### ISSUE TITLE
[Resolve Errors] [Review Warnings] Tables - selectively enable borders based on if the table is overflowing

### ISSUE THREAD

**Issue by shindigira** [cfpb/sbl-frontend#547]
- `useIsOverflowing` hook already added to the app
- Requires ref forwarding on the Table container

**Comment by natalia-fitzgerald** [comment]
Yes, that is the aspect that any visual styling difference would be meant to convey. This is why it isn't ideal when tables that don't require horizontal scrolling receive this bordered styling. Generally I prefer the open styling of no borders (standard table styling). Since our app has the need for some horizontal scrolling tables we end up with visual inconsistency on the page. I'd like to have the horizontal scroll styling (borders) affect only the tables that require it.
